name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output name and type of event
        run: |
          echo "event name is:" ${{ github.event_name }} 
          echo "event type is:" ${{ github.event.action }} 
      
      - name: Output the name of the branch
        run: echo "branch name is:" ${{ github.ref_name }}
      
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: List the files in the repository
        run: |
          echo "The list of repository files is:"
          ls -laR
